Repository Paeti/IPNeuronaleNetze, pull requests merged in 2018-11, with the labels that each got.

#2 enh(global): Added small CI testfile and makefile
  .drone.yml
  Makefile
Labels: enhancement

#7 Enh/prototype webfrontend 5
  web/custom.js
  web/index.html
  web/style.css
  web/userForm.png
Labels: enhancement

#10 enh/init_contributing_9
  CONTRIBUTING.md
  README.md
Labels: enhancement

#14 fix/fix_link_11
  README.md
Labels: bug

#15 project_structure/add_folder_13
  data/.keep
  docs/.keep
Labels: project structure

#16 project_structure/add_dockerfile_12
  Dockerfile
Labels: project structure

#22 refactor/refactor_readme_17
  README.md
Labels: refactor

#23 project_structure/add_new_ci_pipeline_19
  .drone.yml
  Dockerfile
Labels: project structure

#26 Research/research modell to use 8
  docs/.keep
  docs/research_result_datasets.md
  docs/research_results.md
Labels: research

#29 Research/research datasets 25
  docs/research_result_datasets.md
Labels: research

#30 Research/research vgg 16 extended 24
  docs/research_results_extended_vgg_16.md
  docs/research_summarize_
Labels: research
